-- ============================================================
-- STOCK BLOOM - ESQUEMA PARA RENDER POSTGRES
-- Descripcion:
-- Ejecuta este script en la base PostgreSQL de Render antes de
-- iniciar el backend por primera vez. Crea tablas, relaciones,
-- validaciones, indices, permisos base y un administrador inicial.
-- ============================================================

-- Punto de rubrica: Diseno fisico de base de datos.
-- Descripcion: Catalogo principal de plantas con restricciones para
-- evitar valores negativos en stock y precios.
CREATE TABLE IF NOT EXISTS planta (
  id_planta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_comun VARCHAR(100) NOT NULL,
  nombre_cientifico VARCHAR(150),
  stock INTEGER NOT NULL DEFAULT 0,
  ambiente VARCHAR(60) NOT NULL,
  temporada VARCHAR(60) NOT NULL,
  categoria VARCHAR(100) NOT NULL,
  precio_mayoreo NUMERIC(10,2) NOT NULL DEFAULT 0,
  precio_menudeo NUMERIC(10,2) NOT NULL DEFAULT 0,
  descripcion VARCHAR(255),
  CONSTRAINT chk_planta_stock CHECK (stock >= 0),
  CONSTRAINT chk_planta_precio_mayoreo CHECK (precio_mayoreo >= 0),
  CONSTRAINT chk_planta_precio_menudeo CHECK (precio_menudeo >= 0)
);

-- Punto de rubrica: Administracion, seguridad y control de acceso.
-- Descripcion: Usuarios del sistema. La columna activo permite dar de
-- baja personal sin perder sus ventas historicas.
CREATE TABLE IF NOT EXISTS usuario (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  apellidoP VARCHAR(80) NOT NULL,
  apellidoM VARCHAR(80),
  telefono VARCHAR(20) NOT NULL UNIQUE,
  correo VARCHAR(120),
  contrasenia VARCHAR(255) NOT NULL,
  rol VARCHAR(40) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- Punto de rubrica: Roles y permisos.
-- Descripcion: Permisos funcionales que se asignan a usuarios para
-- controlar que modulos puede consultar o modificar cada empleado.
CREATE TABLE IF NOT EXISTS permiso (
  id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_permiso VARCHAR(80) NOT NULL UNIQUE,
  descripcion VARCHAR(180)
);

-- Punto de rubrica: Relacion muchos a muchos.
-- Descripcion: Une usuarios con permisos y evita asignaciones duplicadas.
CREATE TABLE IF NOT EXISTS usuario_permiso (
  id_usuario INTEGER NOT NULL,
  id_permiso INTEGER NOT NULL,
  PRIMARY KEY (id_usuario, id_permiso),
  CONSTRAINT fk_usuario_permiso_usuario
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE CASCADE,
  CONSTRAINT fk_usuario_permiso_permiso
    FOREIGN KEY (id_permiso) REFERENCES permiso(id_permiso) ON DELETE CASCADE
);

-- Punto de rubrica: Transacciones e integridad historica.
-- Descripcion: Encabezado de ventas. Conserva fecha, total y cajero.
CREATE TABLE IF NOT EXISTS venta (
  id_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha TIMESTAMP NOT NULL,
  total NUMERIC(10,2) NOT NULL DEFAULT 0,
  id_usuario INTEGER NOT NULL,
  CONSTRAINT chk_venta_total CHECK (total >= 0),
  CONSTRAINT fk_venta_usuario
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

-- Punto de rubrica: Normalizacion e integridad referencial.
-- Descripcion: Detalle de plantas vendidas por ticket.
CREATE TABLE IF NOT EXISTS detalle_venta (
  id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta INTEGER NOT NULL,
  id_planta INTEGER NOT NULL,
  cantidad INTEGER NOT NULL,
  precio_unitario NUMERIC(10,2) NOT NULL,
  subtotal NUMERIC(10,2) NOT NULL,
  CONSTRAINT chk_detalle_cantidad CHECK (cantidad > 0),
  CONSTRAINT chk_detalle_precio CHECK (precio_unitario >= 0),
  CONSTRAINT chk_detalle_subtotal CHECK (subtotal >= 0),
  CONSTRAINT fk_detalle_venta
    FOREIGN KEY (id_venta) REFERENCES venta(id_venta) ON DELETE CASCADE,
  CONSTRAINT fk_detalle_planta
    FOREIGN KEY (id_planta) REFERENCES planta(id_planta)
);

-- Punto de rubrica: Control de produccion.
-- Descripcion: Lotes internos de siembra y cosecha asociados al catalogo.
CREATE TABLE IF NOT EXISTS produccion (
  id_produccion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_planta INTEGER NOT NULL,
  cantidad INTEGER NOT NULL,
  fecha_siembra DATE NOT NULL,
  fecha_cosecha DATE,
  observaciones TEXT,
  CONSTRAINT chk_produccion_cantidad CHECK (cantidad > 0),
  CONSTRAINT fk_produccion_planta
    FOREIGN KEY (id_planta) REFERENCES planta(id_planta) ON DELETE CASCADE
);

-- Punto de rubrica: Rendimiento de consultas.
-- Descripcion: Indices para reportes por fecha, ventas y produccion.
CREATE INDEX IF NOT EXISTS idx_venta_fecha ON venta(fecha);
CREATE INDEX IF NOT EXISTS idx_venta_usuario ON venta(id_usuario);
CREATE INDEX IF NOT EXISTS idx_detalle_venta_id_venta ON detalle_venta(id_venta);
CREATE INDEX IF NOT EXISTS idx_detalle_venta_id_planta ON detalle_venta(id_planta);
CREATE INDEX IF NOT EXISTS idx_produccion_id_planta ON produccion(id_planta);

-- Punto de rubrica: Seguridad inicial.
-- Descripcion: Permisos base usados por el backend para asignar accesos.
INSERT INTO permiso (nombre_permiso, descripcion) VALUES
  ('VER_PRODUCTOS', 'Consultar plantas e inventario'),
  ('GESTIONAR_PRODUCTOS', 'Registrar, editar o eliminar plantas y produccion'),
  ('REGISTRAR_VENTA', 'Registrar ventas en punto de venta'),
  ('VER_HISTORIAL_VENTAS', 'Consultar historial y reportes'),
  ('REALIZAR_CORTE', 'Generar cortes y reportes PDF'),
  ('GESTIONAR_USUARIOS', 'Administrar usuarios y privilegios')
ON CONFLICT (nombre_permiso) DO NOTHING;

-- Punto de rubrica: Usuario administrador de arranque.
-- Descripcion: Credenciales temporales para entrar por primera vez.
-- Telefono: 7120000000 | Contrasena: 12345678
-- Cambia estos datos desde el sistema despues del primer ingreso.
INSERT INTO usuario (nombre, apellidoP, apellidoM, telefono, contrasenia, rol, activo)
VALUES ('Jorge', 'Cruz', 'Gonzaga', '7120000000', '12345678', 'Administrador', TRUE)
ON CONFLICT (telefono) DO NOTHING;

INSERT INTO usuario_permiso (id_usuario, id_permiso)
SELECT u.id_usuario, p.id_permiso
FROM usuario u
CROSS JOIN permiso p
WHERE u.telefono = '7120000000'
ON CONFLICT (id_usuario, id_permiso) DO NOTHING;
