import { Injectable, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import { createPool, Pool as MySqlPool, PoolConnection } from 'mysql2/promise';
import { Pool as PgPool, PoolClient } from 'pg';
import '../config/env';

type DbClient = 'mysql' | 'postgres';

type QueryResultTuple = [any, any];

const primaryKeysByTable: Record<string, string> = {
  planta: 'id_planta',
  usuario: 'id_usuario',
  permiso: 'id_permiso',
  venta: 'id_venta',
  detalle_venta: 'id_detalle',
  produccion: 'id_produccion',
};

class PostgresConnection {
  constructor(private readonly client: PoolClient, private readonly normalize: (sql: string, values?: any[]) => { sql: string; values: any[] }) {}

  async beginTransaction() {
    await this.client.query('BEGIN');
  }

  async commit() {
    await this.client.query('COMMIT');
  }

  async rollback() {
    await this.client.query('ROLLBACK');
  }

  async query(sql: string, values: any[] = []): Promise<QueryResultTuple> {
    const normalized = this.normalize(sql, values);
    const result = await this.client.query(normalized.sql, normalized.values);
    return formatPostgresResult(normalized.sql, result);
  }

  release() {
    this.client.release();
  }
}

function formatPostgresResult(sql: string, result: any): QueryResultTuple {
  const isSelectLike = /^\s*(SELECT|SHOW|WITH)\b/i.test(sql);

  if (isSelectLike) {
    return [result.rows, { affectedRows: result.rowCount || 0, rowCount: result.rowCount || 0 }];
  }

  const insertId = result.rows?.[0] ? Object.values(result.rows[0])[0] : undefined;
  return [
    {
      affectedRows: result.rowCount || 0,
      insertId,
      rowCount: result.rowCount || 0,
    },
    undefined,
  ];
}

@Injectable()
export class DatabaseService implements OnModuleDestroy, OnModuleInit {
  private readonly client: DbClient;
  private readonly mysqlPool?: MySqlPool;
  private readonly pgPool?: PgPool;

  constructor() {
    const requestedClient = String(process.env.DB_CLIENT || '').toLowerCase();
    this.client = requestedClient === 'postgres' || requestedClient === 'postgresql' || String(process.env.DATABASE_URL || '').startsWith('postgres')
      ? 'postgres'
      : 'mysql';

    if (this.client === 'postgres') {
      this.pgPool = new PgPool({
        connectionString: process.env.DATABASE_URL || undefined,
        host: process.env.DATABASE_URL ? undefined : process.env.DB_HOST,
        port: process.env.DATABASE_URL ? undefined : Number(process.env.DB_PORT || 5432),
        user: process.env.DATABASE_URL ? undefined : process.env.DB_USER,
        password: process.env.DATABASE_URL ? undefined : process.env.DB_PASSWORD,
        database: process.env.DATABASE_URL ? undefined : process.env.DB_NAME,
        max: Number(process.env.DB_CONNECTION_LIMIT || 10),
        ssl: String(process.env.DB_SSL || '').toLowerCase() === 'true' ? { rejectUnauthorized: false } : undefined,
      });
      return;
    }

    const sslEnabled = String(process.env.DB_SSL || '').toLowerCase() === 'true';

    this.mysqlPool = createPool({
      host: process.env.DB_HOST || 'localhost',
      port: Number(process.env.DB_PORT || 3306),
      user: process.env.DB_USER || 'root',
      password: process.env.DB_PASSWORD || '12345678',
      database: process.env.DB_NAME || 'stockbloomdb',
      waitForConnections: true,
      connectionLimit: Number(process.env.DB_CONNECTION_LIMIT || 10),
      queueLimit: 0,
      ssl: sslEnabled ? { rejectUnauthorized: false } : undefined,
    });
  }

  isPostgres() {
    return this.client === 'postgres';
  }

  async onModuleInit() {
    await this.ensureSchema();
  }

  async ensureSchema() {
    if (!this.isPostgres()) return;

    await this.pgPool.query(`
      CREATE TABLE IF NOT EXISTS planta (
        id_planta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_comun VARCHAR(100) NOT NULL,
        nombre_cientifico VARCHAR(150),
        stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
        ambiente VARCHAR(60) NOT NULL,
        temporada VARCHAR(60) NOT NULL,
        categoria VARCHAR(100) NOT NULL,
        precio_mayoreo NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (precio_mayoreo >= 0),
        precio_menudeo NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (precio_menudeo >= 0),
        descripcion VARCHAR(255)
      )
    `);

    await this.pgPool.query(`
      CREATE TABLE IF NOT EXISTS usuario (
        id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre VARCHAR(80) NOT NULL,
        apellidoP VARCHAR(80) NOT NULL,
        apellidoM VARCHAR(80),
        telefono VARCHAR(20) NOT NULL UNIQUE,
        correo VARCHAR(120),
        contrasenia VARCHAR(255) NOT NULL,
        rol VARCHAR(40) NOT NULL,
        activo BOOLEAN NOT NULL DEFAULT TRUE
      )
    `);

    await this.pgPool.query(`
      CREATE TABLE IF NOT EXISTS permiso (
        id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_permiso VARCHAR(80) NOT NULL UNIQUE,
        descripcion VARCHAR(180)
      )
    `);

    await this.pgPool.query(`
      CREATE TABLE IF NOT EXISTS usuario_permiso (
        id_usuario INTEGER NOT NULL,
        id_permiso INTEGER NOT NULL,
        PRIMARY KEY (id_usuario, id_permiso),
        CONSTRAINT fk_usuario_permiso_usuario
          FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE CASCADE,
        CONSTRAINT fk_usuario_permiso_permiso
          FOREIGN KEY (id_permiso) REFERENCES permiso(id_permiso) ON DELETE CASCADE
      )
    `);

    await this.pgPool.query(`
      CREATE TABLE IF NOT EXISTS venta (
        id_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fecha TIMESTAMP NOT NULL,
        total NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
        id_usuario INTEGER NOT NULL,
        CONSTRAINT fk_venta_usuario
          FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
      )
    `);

    await this.pgPool.query(`
      CREATE TABLE IF NOT EXISTS detalle_venta (
        id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_venta INTEGER NOT NULL,
        id_planta INTEGER NOT NULL,
        cantidad INTEGER NOT NULL CHECK (cantidad > 0),
        precio_unitario NUMERIC(10,2) NOT NULL CHECK (precio_unitario >= 0),
        subtotal NUMERIC(10,2) NOT NULL CHECK (subtotal >= 0),
        CONSTRAINT fk_detalle_venta
          FOREIGN KEY (id_venta) REFERENCES venta(id_venta) ON DELETE CASCADE,
        CONSTRAINT fk_detalle_planta
          FOREIGN KEY (id_planta) REFERENCES planta(id_planta)
      )
    `);

    await this.pgPool.query(`
      CREATE TABLE IF NOT EXISTS produccion (
        id_produccion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_planta INTEGER NOT NULL,
        cantidad INTEGER NOT NULL CHECK (cantidad > 0),
        fecha_siembra DATE NOT NULL,
        fecha_cosecha DATE,
        observaciones TEXT,
        CONSTRAINT fk_produccion_planta
          FOREIGN KEY (id_planta) REFERENCES planta(id_planta) ON DELETE CASCADE
      )
    `);

    await this.pgPool.query('CREATE INDEX IF NOT EXISTS idx_venta_fecha ON venta(fecha)');
    await this.pgPool.query('CREATE INDEX IF NOT EXISTS idx_venta_usuario ON venta(id_usuario)');
    await this.pgPool.query('CREATE INDEX IF NOT EXISTS idx_detalle_venta_id_venta ON detalle_venta(id_venta)');
    await this.pgPool.query('CREATE INDEX IF NOT EXISTS idx_detalle_venta_id_planta ON detalle_venta(id_planta)');
    await this.pgPool.query('CREATE INDEX IF NOT EXISTS idx_produccion_id_planta ON produccion(id_planta)');

    await this.pgPool.query(`
      INSERT INTO permiso (nombre_permiso, descripcion) VALUES
        ('VER_PRODUCTOS', 'Consultar plantas e inventario'),
        ('GESTIONAR_PRODUCTOS', 'Registrar, editar o eliminar plantas y produccion'),
        ('REGISTRAR_VENTA', 'Registrar ventas en punto de venta'),
        ('VER_HISTORIAL_VENTAS', 'Consultar historial y reportes'),
        ('REALIZAR_CORTE', 'Generar cortes y reportes PDF'),
        ('GESTIONAR_USUARIOS', 'Administrar usuarios y privilegios')
      ON CONFLICT (nombre_permiso) DO NOTHING
    `);

    await this.pgPool.query(`
      INSERT INTO usuario (nombre, apellidoP, apellidoM, telefono, contrasenia, rol, activo)
      VALUES ('Jorge', 'Cruz', 'Gonzaga', '7120000000', '12345678', 'Administrador', TRUE)
      ON CONFLICT (telefono) DO NOTHING
    `);

    await this.pgPool.query(`
      INSERT INTO usuario_permiso (id_usuario, id_permiso)
      SELECT u.id_usuario, p.id_permiso
      FROM usuario u
      CROSS JOIN permiso p
      WHERE u.telefono = '7120000000'
      ON CONFLICT (id_usuario, id_permiso) DO NOTHING
    `);
  }

  escapeIdentifier(identifier: string) {
    const cleanIdentifier = identifier.replace(/[`"]/g, '');
    return this.isPostgres() ? `"${cleanIdentifier.replace(/"/g, '""')}"` : `\`${cleanIdentifier.replace(/`/g, '``')}\``;
  }

  private getColumnsSql(tableName: string) {
    return {
      sql: `SELECT column_name AS "Field"
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = $1
            ORDER BY ordinal_position`,
      values: [tableName],
    };
  }

  private addReturningIfNeeded(sql: string) {
    if (/\bRETURNING\b/i.test(sql)) return sql;

    const match = sql.match(/^\s*INSERT\s+INTO\s+"?([a-zA-Z_][\w]*)"?/i);
    if (!match) return sql;

    const primaryKey = primaryKeysByTable[match[1].toLowerCase()];
    return primaryKey ? `${sql} RETURNING "${primaryKey}"` : sql;
  }

  private normalizePostgresSql(sql: string, values: any[] = []) {
    const trimmed = sql.trim();
    const showColumnsMatch = trimmed.match(/^SHOW\s+COLUMNS\s+FROM\s+`?([a-zA-Z_][\w]*)`?$/i);

    if (showColumnsMatch) {
      return this.getColumnsSql(showColumnsMatch[1]);
    }

    let normalized = sql
      .replace(/`([^`]+)`/g, '"$1"')
      .replace(/\bINT\s+AUTO_INCREMENT\s+PRIMARY\s+KEY\b/gi, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
      .replace(/\bDATETIME\b/gi, 'TIMESTAMP')
      .replace(/\bTINYINT\s*\(\s*1\s*\)/gi, 'BOOLEAN')
      .replace(/\bactivo\s*=\s*1\b/gi, 'activo = TRUE')
      .replace(/\bactivo\s*=\s*0\b/gi, 'activo = FALSE')
      .replace(/\bactivo\s*=\s*\?/gi, 'activo = ?')
      .replace(/\bMONTH\s*\(\s*([^)]+?)\s*\)/gi, 'EXTRACT(MONTH FROM $1)::int')
      .replace(/CONCAT\("DEL",\s*id_usuario\)/gi, "CONCAT('DEL', id_usuario)");

    let parameterIndex = 0;
    normalized = normalized.replace(/\?/g, () => `$${++parameterIndex}`);
    normalized = this.addReturningIfNeeded(normalized);

    return { sql: normalized, values };
  }

  async query(sql: string, values?: any[]): Promise<QueryResultTuple> {
    if (this.client === 'mysql') {
      return this.mysqlPool.query(sql, values) as Promise<QueryResultTuple>;
    }

    const normalized = this.normalizePostgresSql(sql, values || []);
    const result = await this.pgPool.query(normalized.sql, normalized.values);
    return formatPostgresResult(normalized.sql, result);
  }

  async getConnection(): Promise<PoolConnection | PostgresConnection> {
    if (this.client === 'mysql') return this.mysqlPool.getConnection();

    const client = await this.pgPool.connect();
    return new PostgresConnection(client, (sql, values) => this.normalizePostgresSql(sql, values));
  }

  async onModuleDestroy() {
    if (this.mysqlPool) await this.mysqlPool.end();
    if (this.pgPool) await this.pgPool.end();
  }
}
