import { Injectable, OnModuleDestroy } from '@nestjs/common';
import { createPool, Pool as MySqlPool, PoolConnection } from 'mysql2/promise';
import { Pool as PgPool, PoolClient } from 'pg';
import '../config/env';

type DbClient = 'mysql' | 'postgres';

type QueryResultTuple = [any, any];

const primaryKeysByTable: Record<string, string> = {
  planta: 'id_planta',
  usuario: 'id_usuario',
  permiso: 'id_permiso',
  venta: 'id_venta',
  detalle_venta: 'id_detalle',
  produccion: 'id_produccion',
};

class PostgresConnection {
  constructor(private readonly client: PoolClient, private readonly normalize: (sql: string, values?: any[]) => { sql: string; values: any[] }) {}

  async beginTransaction() {
    await this.client.query('BEGIN');
  }

  async commit() {
    await this.client.query('COMMIT');
  }

  async rollback() {
    await this.client.query('ROLLBACK');
  }

  async query(sql: string, values: any[] = []): Promise<QueryResultTuple> {
    const normalized = this.normalize(sql, values);
    const result = await this.client.query(normalized.sql, normalized.values);
    return formatPostgresResult(normalized.sql, result);
  }

  release() {
    this.client.release();
  }
}

function formatPostgresResult(sql: string, result: any): QueryResultTuple {
  const isSelectLike = /^\s*(SELECT|SHOW|WITH)\b/i.test(sql);

  if (isSelectLike) {
    return [result.rows, { affectedRows: result.rowCount || 0, rowCount: result.rowCount || 0 }];
  }

  const insertId = result.rows?.[0] ? Object.values(result.rows[0])[0] : undefined;
  return [
    {
      affectedRows: result.rowCount || 0,
      insertId,
      rowCount: result.rowCount || 0,
    },
    undefined,
  ];
}

@Injectable()
export class DatabaseService implements OnModuleDestroy {
  private readonly client: DbClient;
  private readonly mysqlPool?: MySqlPool;
  private readonly pgPool?: PgPool;

  constructor() {
    const requestedClient = String(process.env.DB_CLIENT || '').toLowerCase();
    this.client = requestedClient === 'postgres' || requestedClient === 'postgresql' || String(process.env.DATABASE_URL || '').startsWith('postgres')
      ? 'postgres'
      : 'mysql';

    if (this.client === 'postgres') {
      this.pgPool = new PgPool({
        connectionString: process.env.DATABASE_URL || undefined,
        host: process.env.DATABASE_URL ? undefined : process.env.DB_HOST,
        port: process.env.DATABASE_URL ? undefined : Number(process.env.DB_PORT || 5432),
        user: process.env.DATABASE_URL ? undefined : process.env.DB_USER,
        password: process.env.DATABASE_URL ? undefined : process.env.DB_PASSWORD,
        database: process.env.DATABASE_URL ? undefined : process.env.DB_NAME,
        max: Number(process.env.DB_CONNECTION_LIMIT || 10),
        ssl: String(process.env.DB_SSL || '').toLowerCase() === 'true' ? { rejectUnauthorized: false } : undefined,
      });
      return;
    }

    const sslEnabled = String(process.env.DB_SSL || '').toLowerCase() === 'true';

    this.mysqlPool = createPool({
      host: process.env.DB_HOST || 'localhost',
      port: Number(process.env.DB_PORT || 3306),
      user: process.env.DB_USER || 'root',
      password: process.env.DB_PASSWORD || '12345678',
      database: process.env.DB_NAME || 'stockbloomdb',
      waitForConnections: true,
      connectionLimit: Number(process.env.DB_CONNECTION_LIMIT || 10),
      queueLimit: 0,
      ssl: sslEnabled ? { rejectUnauthorized: false } : undefined,
    });
  }

  isPostgres() {
    return this.client === 'postgres';
  }

  escapeIdentifier(identifier: string) {
    const cleanIdentifier = identifier.replace(/[`"]/g, '');
    return this.isPostgres() ? `"${cleanIdentifier.replace(/"/g, '""')}"` : `\`${cleanIdentifier.replace(/`/g, '``')}\``;
  }

  private getColumnsSql(tableName: string) {
    return {
      sql: `SELECT column_name AS "Field"
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = $1
            ORDER BY ordinal_position`,
      values: [tableName],
    };
  }

  private addReturningIfNeeded(sql: string) {
    if (/\bRETURNING\b/i.test(sql)) return sql;

    const match = sql.match(/^\s*INSERT\s+INTO\s+"?([a-zA-Z_][\w]*)"?/i);
    if (!match) return sql;

    const primaryKey = primaryKeysByTable[match[1].toLowerCase()];
    return primaryKey ? `${sql} RETURNING "${primaryKey}"` : sql;
  }

  private normalizePostgresSql(sql: string, values: any[] = []) {
    const trimmed = sql.trim();
    const showColumnsMatch = trimmed.match(/^SHOW\s+COLUMNS\s+FROM\s+`?([a-zA-Z_][\w]*)`?$/i);

    if (showColumnsMatch) {
      return this.getColumnsSql(showColumnsMatch[1]);
    }

    let normalized = sql
      .replace(/`([^`]+)`/g, '"$1"')
      .replace(/\bINT\s+AUTO_INCREMENT\s+PRIMARY\s+KEY\b/gi, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
      .replace(/\bDATETIME\b/gi, 'TIMESTAMP')
      .replace(/\bTINYINT\s*\(\s*1\s*\)/gi, 'BOOLEAN')
      .replace(/\bactivo\s*=\s*1\b/gi, 'activo = TRUE')
      .replace(/\bactivo\s*=\s*0\b/gi, 'activo = FALSE')
      .replace(/\bactivo\s*=\s*\?/gi, 'activo = ?')
      .replace(/\bMONTH\s*\(\s*([^)]+?)\s*\)/gi, 'EXTRACT(MONTH FROM $1)::int')
      .replace(/CONCAT\("DEL",\s*id_usuario\)/gi, "CONCAT('DEL', id_usuario)");

    let parameterIndex = 0;
    normalized = normalized.replace(/\?/g, () => `$${++parameterIndex}`);
    normalized = this.addReturningIfNeeded(normalized);

    return { sql: normalized, values };
  }

  async query(sql: string, values?: any[]): Promise<QueryResultTuple> {
    if (this.client === 'mysql') {
      return this.mysqlPool.query(sql, values) as Promise<QueryResultTuple>;
    }

    const normalized = this.normalizePostgresSql(sql, values || []);
    const result = await this.pgPool.query(normalized.sql, normalized.values);
    return formatPostgresResult(normalized.sql, result);
  }

  async getConnection(): Promise<PoolConnection | PostgresConnection> {
    if (this.client === 'mysql') return this.mysqlPool.getConnection();

    const client = await this.pgPool.connect();
    return new PostgresConnection(client, (sql, values) => this.normalizePostgresSql(sql, values));
  }

  async onModuleDestroy() {
    if (this.mysqlPool) await this.mysqlPool.end();
    if (this.pgPool) await this.pgPool.end();
  }
}
